
alecrabbit/php-accessories:
  install: default
  script: default

alecrabbit/php-simple-profiler:
  install: default
  script: default

alecrabbit/php-cli-tools:
  install: default
  script: default

alecrabbit/php-console-spinner:
  install: default
  script: default

alecrabbit/php-console-colour:
  install: default
  script: default
